// ═══════════════════════════════════════════════════════════════════
// template.typ — Document engine (Typst)
// ───────────────────────────────────────────────────────────────────
// Professional document template parameterizable by brand AND language.
// Do NOT edit this file to re-brand: edit `brand.typ`.
//
// USAGE:
//   #import "template.typ": *
//   #show: doc.with(
//     title: "Title", subtitle: "Subtitle",
//     doc-label: "Proposal", client: "Client", date: "June 2026",
//     lang: "en",   // "en" (default) or "es" — controls the template chrome
//   )
//   = Heading
//   Content...
//
// LANGUAGE: the cover/header/footer labels and the `yes`/`no` helpers come
//   from `labels` below. Ship-ready: "en" and "es". To add a language, add a
//   new entry to `labels` (e.g. "fr": (...)) with the same keys, then pass
//   lang: "fr". Your document BODY is written in whatever language you want;
//   `lang` only localizes the template's own chrome (and hyphenation).
//
// COMPONENTS: callout[..], dark-callout[..], metric(value, label),
//   chk (checkbox), yes / no, horizontalrule.
//
// PHILOSOPHY (avoid the "auto-generated" look): zero emojis; hierarchy through
//   typography, weight and space (not through color); designed tables; brand cover.
// ═══════════════════════════════════════════════════════════════════

#import "brand.typ": *

// ── Language packs ─────────────────────────────────────────────────
// Add a language by adding an entry with these same keys.
#let labels = (
  en: (
    yes: "Yes", no: "No",
    for-prefix: "For",
    cover-for: "FOR", cover-document: "DOCUMENT", cover-date: "DATE",
    cover-classification: "CLASSIFICATION", cover-prepared-by: "PREPARED BY",
    cover-version: "VERSION",
    default-document: "Document", default-classification: "Confidential",
  ),
  es: (
    yes: "Sí", no: "No",
    for-prefix: "Para",
    cover-for: "PARA", cover-document: "DOCUMENTO", cover-date: "FECHA",
    cover-classification: "CLASIFICACIÓN", cover-prepared-by: "PREPARADO POR",
    cover-version: "VERSIÓN",
    default-document: "Documento", default-classification: "Confidencial",
  ),
)

// current document language (set by `doc`); lets `yes`/`no` localize too
#let doc-lang = state("doc-lang", "en")
#let lab() = labels.at(doc-lang.get(), default: labels.en)

// ── Neutral grays (work with any `primary`) ─────────────────────────
#let muted      = rgb("6E6E6E")    // muted text / labels
#let line-soft  = rgb("D4D4D4")    // dividers
#let fill-zebra = rgb("F5F5F5")    // alternating rows / soft backgrounds

// ── Components ─────────────────────────────────────────────────────
#let yes = context text(fill: primary, weight: "bold")[#lab().yes]
#let no  = context text(fill: muted)[#lab().no]

#let chk = box(width: 8pt, height: 8pt, stroke: 0.9pt + muted, radius: 1.5pt, baseline: 1pt)

#let horizontalrule = { v(0.3em); line(length: 100%, stroke: 0.5pt + line-soft); v(0.3em) }

#let callout(body) = block(
  fill: fill-zebra, stroke: (left: 3pt + primary),
  inset: (x: 14pt, y: 11pt), width: 100%,
  radius: (top-right: 3pt, bottom-right: 3pt),
)[#body]

#let dark-callout(body) = block(
  fill: primary, inset: (x: 16pt, y: 13pt), width: 100%, radius: 3pt,
)[#text(fill: white)[#body]]

#let metric(value, label) = block(
  fill: white, stroke: (top: 3pt + accent),
  inset: (x: 10pt, y: 9pt), width: 100%,
)[#align(center)[
  #text(fill: primary, weight: "bold", size: 17pt, hyphenate: false)[#value]
  #v(2pt)
  #text(fill: muted, size: 8pt)[#label]
]]

// ── Document (wrapper) ─────────────────────────────────────────────
#let doc(
  title: "",
  subtitle: "",
  doc-label: "",
  client: "",
  date: "",
  classification: "",
  version: "v1.0",
  header-title: "",
  lang: "en",
  body,
) = {
  let L = labels.at(lang, default: labels.en)
  doc-lang.update(lang)

  let doc-label-r      = if doc-label != "" { doc-label } else { L.default-document }
  let classification-r = if classification != "" { classification } else { L.default-classification }

  let hl = if header-title != "" { header-title } else { brand-name }
  let header-right = if client != "" { L.for-prefix + " " + client + " · " + classification-r } else { classification-r }
  let para-field   = if client != "" { client } else { "—" }
  let date-field   = if date != "" { date } else { "—" }

  set text(font: ("Helvetica Neue", "Arial"), size: 10.5pt, lang: lang, fill: primary)
  set par(justify: true, leading: 0.78em)
  set list(marker: (text(fill: primary)[—], text(fill: muted)[·]))
  set heading(numbering: none)

  show heading.where(level: 1): it => {
    v(0.6em)
    block(fill: primary, width: 100%, inset: (x: 13pt, y: 11pt), radius: 3pt)[
      #set text(fill: white, weight: "bold", size: 14pt, tracking: 0.2pt)
      #it.body
    ]
    v(0.7em)
  }
  show heading.where(level: 2): it => {
    v(0.9em)
    grid(columns: (4pt, 1fr), gutter: 10pt,
      block(fill: primary, width: 4pt, height: 1.5em),
      align(horizon)[#text(fill: primary, weight: "bold", size: 12pt)[#it.body]],
    )
    v(0.3em)
  }
  show heading.where(level: 3): it => {
    v(0.6em); text(fill: primary.darken(10%), weight: "bold", size: 10.5pt)[#it.body]; v(0.15em)
  }

  set table(
    stroke: (col, row) => (
      top: if row == 0 { none } else { 0.5pt + line-soft },
      bottom: 0.5pt + line-soft, left: none, right: none,
    ),
    fill: (col, row) => (
      if row == 0 { primary } else if calc.odd(row) { fill-zebra } else { white }
    ),
    inset: (x: 9pt, y: 7pt),
  )
  show table.cell.where(y: 0): it => text(fill: white, weight: "bold", size: 9.5pt)[#it]
  // inside tables: left (not justified) and NO hyphenation (avoids "pun-ta", etc.)
  show table: it => {
    set text(hyphenate: false)
    set par(justify: false, leading: 0.62em)
    it
  }

  // pandoc wraps tables in figure → no numbering/caption
  set figure(numbering: none)
  show figure.where(kind: table): it => it.body
  // markdown blockquotes → callout
  show quote.where(block: true): it => callout(it.body)

  set page(
    paper: "a4",
    margin: (top: 2.1cm, bottom: 2.2cm, left: 2.1cm, right: 2.1cm),
    header: context {
      if counter(page).get().first() > 1 [
        #set text(size: 8pt, fill: muted)
        #grid(columns: (1fr, auto),
          align(left)[#hl],
          align(right)[#header-right],
        )
        #line(length: 100%, stroke: 0.5pt + line-soft)
      ]
    },
    footer: context {
      if counter(page).get().first() > 1 [
        #line(length: 100%, stroke: 0.5pt + line-soft)
        #v(3pt)
        #set text(size: 8pt, fill: muted)
        #if logo-dark != none {
          grid(columns: (auto, 1fr, auto), column-gutter: 8pt,
            align(horizon)[#image(logo-dark, height: 9pt)],
            align(left + horizon)[#brand-name · #classification-r],
            align(right + horizon)[#counter(page).display("1 / 1", both: true)],
          )
        } else {
          grid(columns: (1fr, auto),
            align(left)[#brand-name · #classification-r],
            align(right)[#counter(page).display("1 / 1", both: true)],
          )
        }
      ]
    },
  )

  // ── COVER ──────────────────────────────────────────────────────────
  page(margin: 0pt)[
    #block(fill: primary, width: 100%, height: 100%)[
      #set text(fill: white, hyphenate: false)
      #set par(justify: false)
      #pad(left: 3cm, right: 3cm, top: 3.5cm)[
        #if logo-light != none {
          image(logo-light, width: 5cm)
        } else {
          text(size: 30pt, weight: "bold", tracking: 1pt, fill: white)[#wordmark]
        }
        #if eyebrow != none {
          v(0.5em)
          text(fill: secondary, size: 10pt, weight: "bold", tracking: 4pt)[#eyebrow]
        }
        #v(1.3em)
        #text(size: 34pt, weight: "bold", tracking: -0.5pt)[#title]
        #v(0.3em)
        #text(size: 17pt, fill: secondary)[#subtitle]

        #v(3.5cm)
        #line(length: 100%, stroke: 1.5pt + secondary)
        #v(1.2em)
        #grid(columns: (1fr, 1fr, 1fr), gutter: 0pt,
          [#text(size: 8.5pt, fill: secondary.darken(35%))[#L.cover-for] #v(3pt) #text(size: 11pt, weight: "bold")[#para-field]],
          [#text(size: 8.5pt, fill: secondary.darken(35%))[#L.cover-document] #v(3pt) #text(size: 11pt, weight: "bold")[#doc-label-r]],
          [#text(size: 8.5pt, fill: secondary.darken(35%))[#L.cover-date] #v(3pt) #text(size: 11pt, weight: "bold")[#date-field]],
        )
        #v(0.6em)
        #line(length: 100%, stroke: 0.5pt + primary.lighten(25%))
        #v(0.8em)
        #grid(columns: (1fr, 1fr, 1fr), gutter: 0pt,
          [#text(size: 8.5pt, fill: secondary.darken(35%))[#L.cover-classification] #v(3pt) #text(size: 11pt, weight: "bold")[#classification-r]],
          [#text(size: 8.5pt, fill: secondary.darken(35%))[#L.cover-prepared-by] #v(3pt) #text(size: 11pt, weight: "bold")[#brand-name]],
          [#text(size: 8.5pt, fill: secondary.darken(35%))[#L.cover-version] #v(3pt) #text(size: 11pt, weight: "bold")[#version]],
        )
      ]
    ]
  ]

  body
}
